name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    uses: portapps/.github/.github/workflows/app-build.yml@3b19d5c32283b0cd19affa9864488daaeeb5feac # v1.3.0
    permissions:
      contents: write # required to create a GitHub release on push with a tag
