name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    uses: portapps/.github/.github/workflows/app-build.yml@504fdded88e9b82399080e6d228791ab77213aec # v1.2.0
    permissions:
      contents: write # required to create a GitHub release on push with a tag
