name: released

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  release:
    types: [published]

jobs:
  virustotal:
    uses: portapps/.github/.github/workflows/app-virustotal.yml@504fdded88e9b82399080e6d228791ab77213aec # v1.2.0
    permissions:
      contents: write # required to write GitHub Release body
    secrets:
      vt_api_key: ${{ secrets.VT_API_KEY }}
      vt_monitor_api_key: ${{ secrets.VT_MONITOR_API_KEY }}
